#server容器配置
server:
  port: 8080

#spring上下文配置
spring:
  datasource:
    url: jdbc:mysql://47.93.233.214:3306/bankcourt
    username: root
    password: 123456a
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis配置
mybatis:
  #实体类所做包
  type-aliases-package: com.born.bc.body.*.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*/*.xml
  
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    


  